-- ============================================================
-- HANA Table: COM_EXAMPLE_ASNSCAN_ASNSTAGING
-- (Auto-generated by CAP from db/schema.cds on cds build)
-- Run manually only if deploying without HDI container.
-- ============================================================

CREATE COLUMN TABLE "COM_EXAMPLE_ASNSCAN_ASNSTAGING" (
    "STAGINGID"   NVARCHAR(20)   NOT NULL,   -- e.g. STG-2024-0001
    "VENDOR"      NVARCHAR(100),
    "VENDORID"    NVARCHAR(20),
    "PO"          NVARCHAR(20),              -- Purchase Order number
    "MATERIAL"    NVARCHAR(30),
    "QTY"         NVARCHAR(20),              -- "2400 EA"
    "BATCH"       NVARCHAR(30),
    "PLANT"       NVARCHAR(20),
    "WEIGHT"      NVARCHAR(20),
    "INCO"        NVARCHAR(50),              -- Incoterms
    "DELIVDATE"   NVARCHAR(10),              -- YYYY-MM-DD
    "DOCUMENTURL" NVARCHAR(500),             -- Object Store URL
    "STATUS"      NVARCHAR(20)  DEFAULT 'Pending',
                                             -- Pending | Processed | Under Review | Error
    "CREATEDAT"   TIMESTAMP,
    "MODIFIEDAT"  TIMESTAMP,
    PRIMARY KEY ("STAGINGID")
);

-- Index for status-based filtering in Control Tower
CREATE INDEX "IDX_ASN_STATUS" ON "COM_EXAMPLE_ASNSCAN_ASNSTAGING" ("STATUS");
CREATE INDEX "IDX_ASN_VENDOR" ON "COM_EXAMPLE_ASNSCAN_ASNSTAGING" ("VENDOR");
CREATE INDEX "IDX_ASN_CREATEDAT" ON "COM_EXAMPLE_ASNSCAN_ASNSTAGING" ("CREATEDAT" DESC);

-- ============================================================
-- NOTE: When using CAP with HDI (recommended for BTP CF),
-- the table is created automatically via:
--   cds build --production
--   cf push  (mta.yaml handles HDI container binding)
-- ============================================================
